<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateSalesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('sales', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->unsigned()->index();
//            $table->integer('card_id')->unsigned()->index();
            $table->integer('game_id')->unsigned()->index();
            $table->float('profit');
            $table->string('description', 500)->nullable();
            $table->timestamps();
        });

        DB::table('sales')->insert(
            [
                ['user_id' => '1', 'game_id' => '38', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 1), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 1)],
                ['user_id' => '1', 'game_id' => '38', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 1), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 1)],
                ['user_id' => '1', 'game_id' => '38', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 1), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 1)],
                ['user_id' => '1', 'game_id' => '37', 'profit' => '0.06', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 1), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 1)],
                ['user_id' => '1', 'game_id' => '36', 'profit' => '0.07', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 2)],
                ['user_id' => '1', 'game_id' => '1', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 2)],
                ['user_id' => '1', 'game_id' => '34', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 2)],
                ['user_id' => '1', 'game_id' => '34', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 2)],
                ['user_id' => '1', 'game_id' => '34', 'profit' => '0.06', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 2)],
                ['user_id' => '1', 'game_id' => '34', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 2)],
                ['user_id' => '1', 'game_id' => '34', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 2)],
                ['user_id' => '1', 'game_id' => '34', 'profit' => '0.06', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 2)],
                ['user_id' => '1', 'game_id' => '35', 'profit' => '0.08', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 3), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 3)],
                ['user_id' => '1', 'game_id' => '33', 'profit' => '0.09', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 4), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 4)],
                ['user_id' => '1', 'game_id' => '33', 'profit' => '0.11', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 4), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 4)],
                ['user_id' => '1', 'game_id' => '33', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 4), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 4)],
                ['user_id' => '1', 'game_id' => '33', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 4), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 4)],
                ['user_id' => '1', 'game_id' => '33', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 4), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 4)],
                ['user_id' => '1', 'game_id' => '33', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 4), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 4)],
                ['user_id' => '1', 'game_id' => '32', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 5), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 5)],
                ['user_id' => '1', 'game_id' => '32', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 5), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 5)],
                ['user_id' => '1', 'game_id' => '30', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 7), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 7)],
                ['user_id' => '1', 'game_id' => '30', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 7), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 7)],
                ['user_id' => '1', 'game_id' => '30', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 7), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 7)],
                ['user_id' => '1', 'game_id' => '30', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 7), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 7)],
                ['user_id' => '1', 'game_id' => '30', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 7), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 7)],
                ['user_id' => '1', 'game_id' => '30', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 7), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 7)],
                ['user_id' => '1', 'game_id' => '29', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 7), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 7)],
                ['user_id' => '1', 'game_id' => '29', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 7), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 7)],
                ['user_id' => '1', 'game_id' => '29', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 7), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 7)],
                ['user_id' => '1', 'game_id' => '29', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 7), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 7)],
                ['user_id' => '1', 'game_id' => '29', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 7), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 7)],
                ['user_id' => '1', 'game_id' => '33', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 7), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 7)],
                ['user_id' => '1', 'game_id' => '33', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 8), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 8)],
                ['user_id' => '1', 'game_id' => '31', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 8), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 8)],
                ['user_id' => '1', 'game_id' => '31', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 8), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 8)],
                ['user_id' => '1', 'game_id' => '31', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 8), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 8)],
                ['user_id' => '1', 'game_id' => '32', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 8), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 8)],
                ['user_id' => '1', 'game_id' => '32', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 8), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 8)],
                ['user_id' => '1', 'game_id' => '32', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 8), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 8)],
                ['user_id' => '1', 'game_id' => '31', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 8), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 8)],
                ['user_id' => '1', 'game_id' => '31', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 8), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 8)],
                ['user_id' => '1', 'game_id' => '31', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 8), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 8)],
                ['user_id' => '1', 'game_id' => '31', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 8), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 8)],
                ['user_id' => '1', 'game_id' => '31', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 8), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 8)],
                ['user_id' => '1', 'game_id' => '31', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 8), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 8)],
                ['user_id' => '1', 'game_id' => '28', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 9), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 9)],
                ['user_id' => '1', 'game_id' => '28', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 9), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 9)],
                ['user_id' => '1', 'game_id' => '28', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 9), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 9)],
                ['user_id' => '1', 'game_id' => '27', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 9), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 9)],
                ['user_id' => '1', 'game_id' => '27', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 9), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 9)],
                ['user_id' => '1', 'game_id' => '27', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 9), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 9)],
                ['user_id' => '1', 'game_id' => '28', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 9), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 9)],
                ['user_id' => '1', 'game_id' => '28', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 9), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 9)],
                ['user_id' => '1', 'game_id' => '28', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 9), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 9)],
                ['user_id' => '1', 'game_id' => '28', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 9), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 9)],
                ['user_id' => '1', 'game_id' => '27', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 9), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 9)],
                ['user_id' => '1', 'game_id' => '27', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 9), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 9)],
                ['user_id' => '1', 'game_id' => '27', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 9), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 9)],
                ['user_id' => '1', 'game_id' => '26', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 10), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 10)],
                ['user_id' => '1', 'game_id' => '1', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 10), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 10)],
                ['user_id' => '1', 'game_id' => '25', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 10), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 10)],
                ['user_id' => '1', 'game_id' => '25', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 10), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 10)],
                ['user_id' => '1', 'game_id' => '25', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 10), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 10)],
                ['user_id' => '1', 'game_id' => '26', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 11), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 11)],
                ['user_id' => '1', 'game_id' => '26', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 11), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 11)],
                ['user_id' => '1', 'game_id' => '24', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 12), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 12)],
                ['user_id' => '1', 'game_id' => '25', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 12), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 12)],
                ['user_id' => '1', 'game_id' => '25', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 12), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 12)],
                ['user_id' => '1', 'game_id' => '24', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 12), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 12)],
                ['user_id' => '1', 'game_id' => '24', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 12), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 12)],
                ['user_id' => '1', 'game_id' => '24', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 12), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 12)],
                ['user_id' => '1', 'game_id' => '24', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 12), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 12)],
                ['user_id' => '1', 'game_id' => '25', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 12), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 12)],
                ['user_id' => '1', 'game_id' => '23', 'profit' => '0.06', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 12), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 12)],
                ['user_id' => '1', 'game_id' => '24', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 12), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 12)],
                ['user_id' => '1', 'game_id' => '22', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '22', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '22', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '22', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '22', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '19', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '20', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '19', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '20', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '19', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '20', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '18', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '18', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '18', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '18', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '18', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '18', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '21', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '21', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '17', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '17', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '21', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 13), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 13)],
                ['user_id' => '1', 'game_id' => '17', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 14), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 14)],
                ['user_id' => '1', 'game_id' => '21', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 14), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 14)],
                ['user_id' => '1', 'game_id' => '16', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 14), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 14)],
                ['user_id' => '1', 'game_id' => '16', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 14), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 14)],
                ['user_id' => '1', 'game_id' => '16', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 14), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 14)],
                ['user_id' => '1', 'game_id' => '15', 'profit' => '0.07', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 14), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 14)],
                ['user_id' => '1', 'game_id' => '16', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 14), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 14)],
                ['user_id' => '1', 'game_id' => '15', 'profit' => '0.07', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 14), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 14)],
                ['user_id' => '1', 'game_id' => '15', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 14), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 14)],
                ['user_id' => '1', 'game_id' => '17', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 14), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 14)],
                ['user_id' => '1', 'game_id' => '17', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 14), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 14)],
                ['user_id' => '1', 'game_id' => '14', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 15), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 15)],
                ['user_id' => '1', 'game_id' => '14', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 15), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 15)],
                ['user_id' => '1', 'game_id' => '14', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 15), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 15)],
                ['user_id' => '1', 'game_id' => '14', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 15), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 15)],
                ['user_id' => '1', 'game_id' => '14', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 15), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 15)],
                ['user_id' => '1', 'game_id' => '14', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 15), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 15)],
                ['user_id' => '1', 'game_id' => '14', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 15), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 15)],
                ['user_id' => '1', 'game_id' => '14', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 15), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 15)],
                ['user_id' => '1', 'game_id' => '21', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 16), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 16)],
                ['user_id' => '1', 'game_id' => '13', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 16), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 16)],
                ['user_id' => '1', 'game_id' => '13', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 16), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 16)],
                ['user_id' => '1', 'game_id' => '13', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 16), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 16)],
                ['user_id' => '1', 'game_id' => '11', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 17), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 17)],
                ['user_id' => '1', 'game_id' => '11', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 17), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 17)],
                ['user_id' => '1', 'game_id' => '11', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 17), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 17)],
                ['user_id' => '1', 'game_id' => '11', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 17), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 17)],
                ['user_id' => '1', 'game_id' => '11', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 18), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 18)],
                ['user_id' => '1', 'game_id' => '11', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 18), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 18)],
                ['user_id' => '1', 'game_id' => '12', 'profit' => '0.07', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 19), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 19)],
                ['user_id' => '1', 'game_id' => '1', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '9', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '9', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '9', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '9', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '9', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '10', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '9', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '10', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '10', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '1', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '10', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '10', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '10', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '10', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 20), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 20)],
                ['user_id' => '1', 'game_id' => '8', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 21), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 21)],
                ['user_id' => '1', 'game_id' => '8', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 21), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 21)],
                ['user_id' => '1', 'game_id' => '10', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 21), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 21)],
                ['user_id' => '1', 'game_id' => '8', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 21), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 21)],
                ['user_id' => '1', 'game_id' => '7', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 21), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 21)],
                ['user_id' => '1', 'game_id' => '6', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 22), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 22)],
                ['user_id' => '1', 'game_id' => '6', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 22), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 22)],
                ['user_id' => '1', 'game_id' => '6', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 22), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 22)],
                ['user_id' => '1', 'game_id' => '6', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 22), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 22)],
                ['user_id' => '1', 'game_id' => '6', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 22), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 22)],
                ['user_id' => '1', 'game_id' => '6', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 22), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 22)],
                ['user_id' => '1', 'game_id' => '6', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 22), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 22)],
                ['user_id' => '1', 'game_id' => '6', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 22), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 22)],
                ['user_id' => '1', 'game_id' => '4', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 23), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 23)],
                ['user_id' => '1', 'game_id' => '4', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 23), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 23)],
                ['user_id' => '1', 'game_id' => '4', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 23), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 23)],
                ['user_id' => '1', 'game_id' => '5', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 23), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 23)],
                ['user_id' => '1', 'game_id' => '5', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 23), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 23)],
                ['user_id' => '1', 'game_id' => '5', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 23), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 23)],
                ['user_id' => '1', 'game_id' => '5', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 23), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 23)],
                ['user_id' => '1', 'game_id' => '1', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 23), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 23)],
                ['user_id' => '1', 'game_id' => '5', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 23), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 23)],
                ['user_id' => '1', 'game_id' => '26', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 24), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 24)],
                ['user_id' => '1', 'game_id' => '3', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 24), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 24)],
                ['user_id' => '1', 'game_id' => '26', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 24), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 24)],
                ['user_id' => '1', 'game_id' => '26', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 24), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 24)],
                ['user_id' => '1', 'game_id' => '26', 'profit' => '0.02', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 24), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 24)],
                ['user_id' => '1', 'game_id' => '3', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 25), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 25)],
                ['user_id' => '1', 'game_id' => '3', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 25), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 25)],
                ['user_id' => '1', 'game_id' => '2', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 25), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 25)],
                ['user_id' => '1', 'game_id' => '2', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 25), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 25)],
                ['user_id' => '1', 'game_id' => '2', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 25), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 25)],
                ['user_id' => '1', 'game_id' => '2', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 25), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 25)],
                ['user_id' => '1', 'game_id' => '2', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 25), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 25)],
                ['user_id' => '1', 'game_id' => '2', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 25), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 25)],
                ['user_id' => '1', 'game_id' => '39', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '39', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '39', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '39', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '39', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '39', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '40', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '40', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '40', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '41', 'profit' => '0.06', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '40', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '40', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '41', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '41', 'profit' => '0.06', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '40', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 27), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 27)],
                ['user_id' => '1', 'game_id' => '40', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 28), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 28)],
                ['user_id' => '1', 'game_id' => '40', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 28), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 28)],
                ['user_id' => '1', 'game_id' => '40', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 28), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 28)],
                ['user_id' => '1', 'game_id' => '40', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 28), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 28)],
                ['user_id' => '1', 'game_id' => '42', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 28), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 28)],
                ['user_id' => '1', 'game_id' => '42', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 28), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 28)],
                ['user_id' => '1', 'game_id' => '42', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 28), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 28)],
                ['user_id' => '1', 'game_id' => '42', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 28), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 28)],
                ['user_id' => '1', 'game_id' => '42', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 28), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 28)],
                ['user_id' => '1', 'game_id' => '42', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 28), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 28)],
                ['user_id' => '1', 'game_id' => '1', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 30), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 30)],
                ['user_id' => '1', 'game_id' => '43', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 30), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 30)],
                ['user_id' => '1', 'game_id' => '43', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 30), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 30)],
                ['user_id' => '1', 'game_id' => '44', 'profit' => '0.1', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 31), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 31)],
                ['user_id' => '1', 'game_id' => '45', 'profit' => '0.07', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 31), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 31)],
                ['user_id' => '1', 'game_id' => '45', 'profit' => '0.11', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 31), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 31)],
                ['user_id' => '1', 'game_id' => '45', 'profit' => '0.07', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 31), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 31)],
                ['user_id' => '1', 'game_id' => '45', 'profit' => '0.09', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 31), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 31)],
                ['user_id' => '1', 'game_id' => '45', 'profit' => '0.06', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 31), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 31)],
                ['user_id' => '1', 'game_id' => '45', 'profit' => '0.06', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 31), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 31)],
                ['user_id' => '1', 'game_id' => '43', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 31), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 31)],
                ['user_id' => '1', 'game_id' => '43', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 31), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 31)],
                ['user_id' => '1', 'game_id' => '43', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 31), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 31)],
                ['user_id' => '1', 'game_id' => '43', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 31), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 31)],
                ['user_id' => '1', 'game_id' => '46', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 7, 31), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 7, 31)],
                ['user_id' => '1', 'game_id' => '47', 'profit' => '0.06', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 2)],
                ['user_id' => '1', 'game_id' => '47', 'profit' => '0.06', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 2)],
                ['user_id' => '1', 'game_id' => '47', 'profit' => '0.06', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 2)],
                ['user_id' => '1', 'game_id' => '48', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 2)],
                ['user_id' => '1', 'game_id' => '48', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 2)],
                ['user_id' => '1', 'game_id' => '48', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 2)],
                ['user_id' => '1', 'game_id' => '49', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 2)],
                ['user_id' => '1', 'game_id' => '49', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 2)],
                ['user_id' => '1', 'game_id' => '49', 'profit' => '0.03', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 2), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 2)],
                ['user_id' => '1', 'game_id' => '50', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 3), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 3)],
                ['user_id' => '1', 'game_id' => '50', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 3), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 3)],
                ['user_id' => '1', 'game_id' => '50', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 3), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 3)],
                ['user_id' => '1', 'game_id' => '51', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 3), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 3)],
                ['user_id' => '1', 'game_id' => '51', 'profit' => '0.05', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 3), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 3)],
                ['user_id' => '1', 'game_id' => '51', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 4), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 4)],
                ['user_id' => '1', 'game_id' => '51', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 4), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 4)],
                ['user_id' => '1', 'game_id' => '51', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 4), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 4)],
                ['user_id' => '1', 'game_id' => '51', 'profit' => '0.04', 'created_at' => \Carbon\Carbon::createFromDate(2016, 8, 4), 'updated_at' => \Carbon\Carbon::createFromDate(2016, 8, 4)],
            ]
        );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('sales');
    }
}
